title: Journey of becoming a programmer and building my art brand WITT [.art]
author: Lizzy
email: #your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
 Blog about a womans journey of becoming a professional programmer and working as a freelance artist.

# social links
twitter_username: #your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  #your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
